version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.webapp
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn dummyproject.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - static_volume:/home/dummyproject/web/static
    expose:
      - 8000
    env_file:
      - ./env.webapp
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - ../data-dump:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env.webapp

  nginx:
    build:
      context: ./
      dockerfile: ./Dockerfile.nginx
    volumes:
      - static_volume:/home/dummyproject/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
